import type { Card, Category } from './types';
export const categories: { id: Category; label: string; short: string }[] = [
  { id:'groceries',label:'Groceries',short:'Groceries' }, { id:'dining',label:'Restaurants & cafés',short:'Dining' }, { id:'delivery',label:'Eligible food delivery',short:'Food delivery' }, { id:'gas',label:'Gas & EV charging',short:'Gas & EV' }, { id:'transit',label:'Transit & rideshares',short:'Transit' }, { id:'bills',label:'Recurring bills',short:'Bills' }, { id:'drugstores',label:'Drugstores',short:'Drugstores' }, { id:'entertainment',label:'Entertainment',short:'Entertainment' }, { id:'home',label:'Home improvement',short:'Home improvement' }, { id:'furniture',label:'Furniture',short:'Furniture' }, { id:'hotels',label:'Hotels & motels',short:'Hotels' }, { id:'games',label:'Digital games',short:'Games' }, { id:'fitness',label:'Fitness & sports clubs',short:'Fitness' }, { id:'other',label:'Everything else',short:'Other' }
];
export const selectableCategories = categories.filter(c => !['other', 'delivery'].includes(c.id));
const bmoTerms = 'https://www.bmo.com/popups/main/personal/credit-cards/terms-and-conditions-en.html';
const cibcTerms = 'https://www.cibc.com/en/personal-banking/credit-cards/rewards-and-points/cash-back-benefits.html';
const accelerated: Category[] = ['groceries','gas','transit','dining','delivery','bills'];
const verified = '2026-09-26';
export const cards: Card[] = [
  { id:'bmo-world',issuer:'BMO',name:'CashBack World Elite Mastercard',fee:139,feePeriod:'annual',base:.01,color:'#18475b',verified,
    groups:[{categories:['groceries'],rate:.05,cap:500,period:'monthly'},{categories:['transit'],rate:.04,cap:300,period:'monthly'},{categories:['gas'],rate:.03,cap:300,period:'monthly'},{categories:['bills'],rate:.02,cap:500,period:'monthly'}],
    sources:[{label:'Card & current fee',url:'https://www.bmo.com/en-ca/main/personal/credit-cards/bmo-cashback-world-elite-mastercard/'},{label:'Reward terms',url:bmoTerms}],note:'Monthly caps: $500 groceries, $300 transit, $300 gas/EV, $500 recurring bills; then 1%. Canadian merchant requirements apply.' },
  { id:'bmo-free',issuer:'BMO',name:'CashBack Mastercard',fee:0,feePeriod:'annual',base:.005,color:'#24728a',verified,
    groups:[{categories:['groceries'],rate:.03,cap:500,period:'monthly'},{categories:['bills'],rate:.01,cap:500,period:'monthly'}],sources:[{label:'Rates & caps',url:bmoTerms},{label:'Card details',url:'https://www.bmo.com/main/personal/credit-cards/bmo-cashback-mastercard/'}],note:'3% on the first $500 of groceries and 1% on the first $500 of recurring bills per billing cycle; then 0.5%.' },
  { id:'tangerine',issuer:'Tangerine',name:'Money-Back Credit Card',fee:0,feePeriod:'annual',base:.005,color:'#a94e22',verified,groups:[],selectable:true,
    sources:[{label:'Card details',url:'https://www.tangerine.ca/en/personal/spend/credit-cards'},{label:'Reward terms',url:'https://www.tangerine.ca/en/legal/credit-card-cardholder-agreement'}],note:'Choose two unlimited 2% categories, or three when rewards are deposited to a Tangerine Savings Account. Everything else earns 0.5%. Foreign-currency spending is excluded from this domestic budget model.' },
  { id:'simplii',issuer:'Simplii',name:'Cash Back Visa',fee:0,feePeriod:'annual',base:.005,color:'#4c395f',verified,
    groups:[{categories:['dining','delivery'],rate:.04,cap:5000,period:'annual'},{categories:['gas','groceries','drugstores','bills'],rate:.015,cap:15000,period:'annual'}],sources:[{label:'Rates, caps & availability',url:'https://www.simplii.com/en/faq.html'}],note:'Dining has a $5,000 annual cap; gas, groceries, drugstores and recurring bills share a $15,000 annual cap. Then 0.5%. Not available in Quebec. Delivery earns dining rates only when coded as a restaurant.' },
  { id:'cibc-free',issuer:'CIBC',name:'Dividend Visa',fee:0,feePeriod:'annual',base:.005,color:'#8f3945',verified,
    groups:[{categories:accelerated,rate:.01,cap:20000,period:'annual',totalSpendCap:30000},{categories:['groceries'],rate:.02}],sources:[{label:'Card details',url:'https://www.cibc.com/en/personal-banking/credit-cards/all-credit-cards/dividend-visa-card.html'},{label:'Reward terms',url:cibcTerms}],note:'Accelerated rates stop at $20,000 in combined eligible spending or $30,000 total annual spending, whichever comes first; then 0.5%. Delivery must be coded as dining.' },
  { id:'cibc-infinite',issuer:'CIBC',name:'Dividend Visa Infinite',fee:120,feePeriod:'annual',base:.01,color:'#512f39',verified,
    groups:[{categories:accelerated,rate:.02,cap:20000,period:'annual',totalSpendCap:50000},{categories:['groceries','gas'],rate:.04}],sources:[{label:'Card details',url:'https://www.cibc.com/en/personal-banking/credit-cards/all-credit-cards/dividend-visa-infinite-card.html'},{label:'Benefits & cap rules',url:'https://www.cibc.com/content/dam/personal_banking/credit_cards/agreements_and_insurance/dividend-infinite-bengd-en.pdf'}],note:'Accelerated rates stop at $20,000 in combined eligible spending or $50,000 total annual spending, whichever comes first; then 1%. Delivery must be coded as dining.' },
  { id:'rbc',issuer:'RBC',name:'Cash Back Preferred World Elite',fee:99,feePeriod:'annual',base:.01,color:'#3a527a',verified,
    groups:[{categories:categories.map(c=>c.id),rate:.015,cap:25000,period:'annual'}],sources:[{label:'Card, rates & fee',url:'https://www.rbcroyalbank.com/credit-cards/cash-back/rbc-preferred-world-elite-mastercard.html'}],note:'1.5% on the first $25,000 of total annual purchases; then 1%.' },
  { id:'scotia',issuer:'Scotiabank',name:'Momentum Visa Infinite +',fee:120,feePeriod:'annual',base:.01,color:'#79332e',verified,
    groups:[{categories:['groceries','bills'],rate:.04,cap:25000,period:'annual'},{categories:['gas','transit','delivery'],rate:.02,cap:25000,period:'annual'}],sources:[{label:'Card details',url:'https://www.scotiabank.com/ca/en/personal/credit-cards/visa/momentum-infinite-card.html'},{label:'Reward terms',url:'https://www.scotiabank.com/terms/momentumvisainfiniteplus'}],note:'Groceries and bills share a $25,000 annual cap. Gas/EV, transit and eligible food delivery share another $25,000 cap; then 1%. Food delivery eligibility depends on the service.' }
];
